name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Cache ðŸ’µ
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install ðŸ“¦
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap
      - name: Build ðŸ”§
        run: npm run build

  eslint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: ESLint âœ¨
        run: npm run lint:es

  stylelint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Stylelint âœ¨
        run: npm run lint:style

  prettier:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prettier âœ¨
        run: npm run lint:prettier

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Test ðŸ§ª
        run: npm run coverage
      - name: Codecov â˜‚
        uses: codecov/codecov-action@v1
        with:
          directory: coverage
