name: Review

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install ðŸ“¦
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build Sassdoc ðŸ’„
        run: npm run build:sassdoc -- --dest website/static/sassdoc
      - name: Build Storybook ðŸ“š
        run: npm run build:stories -- -- --output-dir ../../website/static/storybook
      - name: Build docs ðŸ“„
        run: npm run build:docs
        env:
          BASE_URL: /${{ github.head_ref }}/
      - name: Upload artifact â¬†
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.head_ref }}
          path: public
      - name: Deploy ðŸš€
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID }}
          SOURCE_DIR: public
          DEST_DIR: ${{ github.head_ref }}
      - name: Clean ðŸ§¹
        if: github.event.pull_request.merged == true
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          PATH_TO_DELETE: ${{ github.head_ref }}
